export interface Comercio {
    id: number,
    nit: string,
    matricula: string,
    razon_social: string,
    nombre: string,
    actividad: string,
    direccion: string,
    municipio: string,
    email: string,
    ano: number,
    fecha_matricula: Date,
    fecha_renovacion: Date,
    telefono1: number,
    telefono2: number,
    telefono3: number,
    ciiu1: string,
    ciiu2: string,
    ciiu3: string,
    ciiu4: string,
}